### ISSUE TITLE
win10 is ok,but error in ubuntu server

### ISSUE THREAD

**Issue by yurokn** [dividab/tsconfig-paths#188] opened 2022-01-10 04:37 UTC
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/@shared/dataModelTypes/models/helpers'
Require stack:
- /root/Nova/dist-server/preload/modelsAPIs/utils.js
- /root/Nova/dist-server/service/db/index.js
- /root/Nova/dist-server/preload/workspacesAPIs/index.js
- /root/Nova/dist-server/server/controller/getApis.js
- /root/Nova/dist-server/server/router/getApis.js
- /root/Nova/dist-server/server/router/index.js
- /root/Nova/dist-server/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (/root/Nova/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Nova/dist-server/preload/modelsAPIs/utils.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Nova/dist-server/preload/modelsAPIs/utils.js',
    '/root/Nova/dist-server/service/db/index.js',
    '/root/Nova/dist-server/preload/workspacesAPIs/index.js',
    '/root/Nova/dist-server/server/controller/getApis.js',
    '/root/Nova/dist-server/server/router/getApis.js',
    '/root/Nova/dist-server/server/router/index.js',
    '/root/Nova/dist-server/server/index.js'
  ]
}

**Comment by cdpark0530** [comment] 2022-03-14 03:53
I guess this caused by this issue: https://github.com/dividab/tsconfig-paths/issues/194

**Comment by jonaskello** [comment] 2022-03-14 10:58
Fixed by #180

**Closed by jonaskello** 2022-03-14 10:58 UTC
